ARG DOCKER_REGISTRY=docker.m.daocloud.io/library
FROM ${DOCKER_REGISTRY}/node:20-alpine AS builder

WORKDIR /app

COPY .npmrc package.json package-lock.json ./

RUN npm ci

COPY index.html nginx.conf postcss.config.js tailwind.config.js tsconfig.json tsconfig.node.json vite.config.ts ./
COPY src ./src

RUN npm run build

FROM ${DOCKER_REGISTRY}/nginx:1.27-alpine

RUN apk add --no-cache wget tzdata

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
